### ISSUE TITLE
Not working on Android 6

### ISSUE THREAD

**Issue by juliusmh** [luv/mockgeofix#3]
Even though I can connect using telnet and run the commans with status OK, the GPS-Location is not changing. Im running Android 6 (CyanogenMod 13) on my Galaxy S4.

**Comment by luv** [comment]
Hi!

Can you please give an example command you run?

Did you disable all geolocation sources but GPS?

How do you verify the location is changing or not? (btw. GPS Dump from Zach Rogers is perfect for this https://play.google.com/store/apps/details?id=org.ZachR.GPSDump )

**Comment by juliusmh** [comment]
Okey I just checked it and i realized that the error was due to my client application. It had an bug when not provided with correct altitude values and i submitted only long / lat values. Thanks for your quick reply anyway!
