### ISSUE TITLE
Doesn't seem to work for apps that use Google API FusedLocation

### ISSUE THREAD

**Issue by kohenkatz** [luv/mockgeofix#4]
This app works very well when I test it using Waze - I see my location in Waze jump when I send `gps fix` commands.

However, my app uses `LocationServices.FusedLocationApi` from the Google Play API (as Google is trying to get everyone to do) and that doesn't follow these updates.

Based on my research, I believe that it would need to call `setMockMode` and `setMockLocation` on the `FusedLocationApi` in addition to calling methods on the old `LocationManager`.

**Comment by kohenkatz** [comment]
If you want, I can do a Pull Request to add this, but I don't want to do the work unless you are interested.

I am also not sure of how to set this up so that people who don't have Google Play Services (Kindle, etc.) could still use it with the old provider.

**Comment by luv** [comment]
Hi!

Thanks for reporting. I totally understand you are not interested putting in the work unless you know it would get merged :).

Regarding FusedLocationApi, I am not all that support it doesn not work as it uses  location data from several provides, so mocking the GPS provider is not enough, that makes sense. If it's easy to add support for mocking FusedLocation I am all for it! Do you think this should be configurable or simply always enabled (as long as Play Services is installed on the device) ?

> I am also not sure of how to set this up so that people who don't have Google Play Services (Kindle, etc.) could still use it with the old provider.

Indeed, this is gonna make things messy but I really don't want MockGeoFix to hard depend od Play Services.

**Comment by kohenkatz** [comment]
I just updated my earlier comment with a way to handle it, though I currently don't have any non-Google-Play-enabled devices to test.

**Comment by luv** [comment]
Cool. Other approach could be something like this https://github.com/luv/mockgeofix/blob/master/app/src/main/java/github/luv/mockgeofix/MockLocationProvider.java#L119 ... whatever works better.

I can test on CyanogenMod without Google Play, no probs.

**Comment by kohenkatz** [comment]
Interestingly, I rebooted my device (for entirely unrelated reasons) and now this *does* work without any changes. I'm guessing that there was some problem with my phone that prevented it from working.
