### ISSUE TITLE
Ability to ignore checksums

### ISSUE THREAD

**Issue by BoD** [luv/mockgeofix#5]
I've made a script that generates `geo nmea` commands, and they work with the emulator.

While working on this, I noticed the emulator actually ignores the checksum of these commands, and so my script simply puts `*00` for the value.

Now I've just found this tool, and it is exactly what I needed :)  Except it actually enforces a correct checksum, and so my little script doesn't work :)

Of course I will fix it to generate correct checksums, but I was wondering if this checking in mockgeofix was really necessary, as it creates an inconsistency between the emulator's behavior and a real device's.  Maybe this could be disabled in a setting...

**Comment by luv** [comment]
Hi

I had a quick look at the emulator source code and it passes the nmea sentence as is to the AVD https://android.googlesource.com/platform/external/qemu/+/emu-1.5-release/android/gps.c#23 - so I'm thinking some android builds run in the emulator might ignore the checksum but other builds might require the checksum to be correct.

Simply ignoring the checksum in MockGeoFix might cause (backwards) compatibility issues for someone. Adding a option to ignore the checksum sounds good. If you create a PR I will merge and release a new version :).

**Comment by BoD** [comment]
Thanks for the quick reply.

Well, fixing my script to have a correct checksum was easier than I thought ;) So I think this option is not really useful after all...

But now that I can try my script, I'm having another problem (I'll open a different issue for it)

Thanks!

**Comment by luv** [comment]
I'm closing this as "won't fix".

Should anyone want the option to ignore nmea checksum in MockGeoFix, feel free to reopen (or better yet create a PR).
